global:
    scrape_interval: 1s
scrape_configs:
    - job_name: 'prometheus'
      static_configs:
        - targets: ['localhost:9090']
    
    - job_name: 'rpi'
      static_configs:
        - targets: [rpi:5000]
