repositories:
  - name: stable
    url: https://charts.helm.sh/stable
  - name: kubernetes-dashboard
    url: https://kubernetes.github.io/dashboard/
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts
  - name: grafana
    url: https://grafana.github.io/helm-charts
  - name: harbor
    url: https://helm.goharbor.io
  - name: fairwinds-stable
    url: https://charts.fairwinds.com/stable


releases:
  - name: traefik
    namespace: default
    chart: stable/traefik
    version: 1.87.7
    installed: true
    values:
      - values/traefik.yaml
  - name: kubernetes-dashboard
    namespace: kube-system
    chart: kubernetes-dashboard/kubernetes-dashboard
    version: 4.0.0
    installed: false
    values:
      - values/kubernetes-dashboard.yaml
  - name: kube-ops-view
    namespace: default
    chart: stable/kube-ops-view
    version: 1.2.4
    installed: true
    values:
      - values/kube-ops-view.yaml
  - name: prometheus
    namespace: monitoring
    chart: prometheus-community/prometheus
    version: 13.2.1
    installed: false
    values:
      - values/prometheus.yaml
  - name: grafana
    namespace: monitoring
    chart: grafana/grafana
    version: 6.2.0
    installed: false
    values:
      - values/grafana.yaml
  - name: harbor
    namespace: default
    chart: harbor/harbor
    version: 1.5.3
    installed: false
    values:
      - values/harbor.yaml
  - name: goldilocks
    namespace: default
    chart: fairwinds-stable/goldilocks
    version: 3.2.1
    installed: false
    values:
      - values/goldilocks.yaml